name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "scuttlebutt/**"
      - "scuttlebutt-*/**"


env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check (fmt, dependency check, clippy, test)
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargolint-${{ hashFiles('Cargo.lock') }}
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: -- --test-threads 1
