name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "chitchat/**"
      - "chitchat-*/**"

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check (fmt, dependency check, clippy, test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rustup
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
      - name: Setup stable Rust Toolchain
        run: rustup show
      - name: Setup nightly Rust Toolchain (for rustfmt)
        run: rustup toolchain install nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargolint-${{ hashFiles('Cargo.lock') }}
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --release -- --test-threads 1
